# Configuration of the grid map filter chain which calculates traversibility and occupancy based on surface normals
grid_map_filters:

  - name: buffer_normalizer
    type: gridMapFilters/BufferNormalizerFilter

  
  # Compute the surface normals.
  - name: surface_normals
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: elevation
      output_layers_prefix: normal_vectors_
      radius: 0.1
      normal_vector_positive_axis: z


  # Visualize surface normals as color layer.
  - name: normal_color_map
    type: gridMapFilters/NormalColorMapFilter
    params:
      input_layers_prefix: normal_vectors_
      output_layer: normal_color

  # Compute the slope based of the surface normals.
  - name: slope
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: slope
      expression: acos(normal_vectors_z)

  # Scale the slope layer.
  - name: traversability_slope
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability
      expression: (slope / 0.6)


  # Duplicate traversibility layer to create occupancy layer.
  - name: duplicate
    type: gridMapFilters/DuplicationFilter
    params:
      input_layer: traversability
      output_layer: occupancy

  # # Set lower threshold on occupancy layer.
  - name: traversability_lower_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      layer: occupancy
      lower_threshold: 1.0
      set_to: .nan

  # # Set upper threshold on occupancy layer.
  - name: traversability_upper_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      layer: occupancy
      upper_threshold: 1.0
      set_to: 1.0 

  