# Parameters for converting the grid map to an octomap
octomap_to_gridmap_demo:
  octomap_service_topic: "/octomap_binary"
  min_z: -2.0
  max_z: 2.0

# Parameters to convert the filtered grid map to an OccupancyGrid
grid_map_visualization:
  grid_map_topic: /grid_map_filter_demo/filtered_map
  grid_map_visualizations:
    - name: traversability_grid
      type: occupancy_grid
      params:
        layer: traversability
        data_min: 0.0
        data_max: 1.0
    - name: traversability_binary_grid
      type: occupancy_grid
      params:
        layer: occupancy
        data_min: 0.0
        data_max: 1.0
    - name: surface_normals
      type: vectors
      params:
        layer_prefix: normal_vectors_
        position_layer: elevation
        scale: 0.2
        line_width: 0.0065
        color: 15600153 # red
   


  